describe('Planos - Plano - Normal', function () {

    beforeEach(() => {
        cy.visit('http://swarm2.pactosolucoes.com.br:8014/LoginApp/teste')
        cy.get('#fmLay\\:usernameLoginZW').click({ force: true }).type('Pactobr')
        cy.get('#fmLay\\:pwdLoginZW').click({ force: true }).type('123')
        cy.get('#fmLay\\:btnEntrar').click({ force: true })
        cy.get(':nth-child(1) > a > .lgmodule > img').click({ force: true })
        cy.get('#form\\:lupaAtiva').click({ force: true })
        cy.get('.panelBusca').type('Plano')
        cy.contains('Plano').click()
        cy.wait(5000)
    })

    // CASO DE TESTE 1: INCLUIR CADASTRO - NORMAL
    it('Incluir Plano - Normal', function () {
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        cy.get('#plano-normal > .content').click({ force: true })
        // PÁGINA - DADOS BÁSICOS
        cy.get('pacto-cat-form-input').type('Teste automatizado')
        cy.get('input[placeholder="__/__/____"]').eq(0).click({ force: true })
            .type('20012020')
        cy.get('input[placeholder="__/__/____"]').eq(1).click({ force: true })
            .type('20012025')
        cy.get('input[placeholder="__/__/____"]').eq(2).click({ force: true })
            .type('20012025')
        cy.get('pacto-cat-button').eq(0).click({ force: true })
        // PÁGINA - DURAÇÃO E VALORES
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('BOXE')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('FAZ TUDO')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('Livre')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(3).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('pacto-column-input-decimal').eq(0).type('2')
        cy.get('pacto-column-input-decimal').eq(1).type('20.00')
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - PRODUTOS E SERVIÇOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('ADESÃO PLANO RECORRENTE')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('pacto-column-input-decimal').type('50.00')
        cy.get('.checkmark-outline').click({ force: true })
        cy.get('#element-3-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - DADOS CONTRATUAIS
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(0).type('NOME DA EMPRESA | CPS 2019')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('[label="Percentual da multa de cancelamento"]').type("50")
        cy.get('.checkmark-outline').eq(2).click({ force: true })
        cy.get('pacto-cat-button').eq(2).click({ force: true })
        // PÁGINA - CONFIGURAÇÕES AVANÇADAS
        cy.contains('Renovação automática').click({ force: true })
        cy.get('[label="Ativar renovação automática"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Renovar produtos obrigatórios"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Não renovar contrato com parcela vencida em aberto"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - CONDIÇÃO DE PAGAMENTO
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('EM 3 VEZES')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('500.00')
        cy.get('#element-2-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
    })

    // CASO DE TESTE 2: EDITAR CADASTRO - NORMAL
    it('Editar Plano - Normal', function () {
        cy.get('#input-busca-rapida').type('Teste automatizado')
        cy.wait(5000)
        cy.get('#ddaction-0').click({ force: true })
        cy.get('#ddAction-0-editar').click({ force: true })
        // PÁGINA - DADOS BÁSICOS
        cy.get('pacto-cat-form-input').type('Teste automatizado')
        cy.get('input[placeholder="__/__/____"]').eq(0).click({ force: true })
            .type('20012019')
        cy.get('input[placeholder="__/__/____"]').eq(1).click({ force: true })
            .type('20012026')
        cy.get('input[placeholder="__/__/____"]').eq(2).click({ force: true })
            .type('20012026')
        cy.get('pacto-cat-button').eq(0).click({ force: true })
        // PÁGINA - DURAÇÃO E VALORES
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('BOXE')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('FAZ TUDO')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('Livre')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(3).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('pacto-column-input-decimal').eq(0).type('12')
        cy.get('pacto-column-input-decimal').eq(1).type('120.00')
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - PRODUTOS E SERVIÇOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('ADESÃO PLANO RECORRENTE')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('pacto-column-input-decimal').type('500.00')
        cy.get('.checkmark-outline').click({ force: true })
        cy.get('#element-3-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - DADOS CONTRATUAIS
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(0).type('NOME DA EMPRESA | CPS 2019')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('[label="Percentual da multa de cancelamento"]').type("500")
        cy.get('.checkmark-outline').eq(2).click({ force: true })
        cy.get('pacto-cat-button').eq(2).click({ force: true })
        // PÁGINA - CONFIGURAÇÕES AVANÇADAS
        cy.contains('Renovação automática').click({ force: true })
        cy.get('[label="Ativar renovação automática"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Renovar produtos obrigatórios"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Não renovar contrato com parcela vencida em aberto"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - CONDIÇÃO DE PAGAMENTO
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('EM 12 VEZES')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('5000.00')
        cy.get('#element-2-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
    })

    // CASO DE TESTE 3: EXCLUIR CADASTRO - NORMAL
    it.only('Excluir Plano - Normal', function () {
        cy.get('#input-busca-rapida').type('Teste automatizado')
        cy.wait(5000)
        cy.get('#ddaction-0').click()
        cy.get('#ddAction-0-excluir').click()
    })

})