describe('Planos - Plano - Recorrência', function () {

    beforeEach(() => {
        cy.visit('http://swarm2.pactosolucoes.com.br:8014/LoginApp/teste')
        cy.get('#fmLay\\:usernameLoginZW').click({ force: true }).type('Pactobr')
        cy.get('#fmLay\\:pwdLoginZW').click({ force: true }).type('123')
        cy.get('#fmLay\\:btnEntrar').click({ force: true })
        cy.get(':nth-child(1) > a > .lgmodule > img').click({ force: true })
        cy.get('#form\\:lupaAtiva').click({ force: true })
        cy.get('.panelBusca').type('Plano')
        cy.contains('Plano').click()
        cy.wait(5000)
    })

    // CASO DE TESTE 1: INCLUIR CADASTRO - RECORRÊNCIA
    it.only('Incluir Plano - Recorrência', function () {
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        cy.get('#plano-recorrencia > .content').click({ force: true })
        // PÁGINA - DADOS BÁSICOS
        cy.get('pacto-cat-form-input').type('Teste automatizado')
        cy.get('input[placeholder="__/__/____"]').eq(0).click({ force: true })
            .type('20012020')
        cy.get('input[placeholder="__/__/____"]').eq(1).click({ force: true })
            .type('20012025')
        cy.get('input[placeholder="__/__/____"]').eq(2).click({ force: true })
            .type('20012025')
        cy.get('pacto-cat-button').eq(0).click({ force: true })
        // PÁGINA - MODALIDADES
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('FAZ TUDO')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - HORÁRIOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('500.00')
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('1500.00')
        cy.get('#element-1-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - PRODUTOS E SERVIÇOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('ADESÃO PLANO RECORRENTE')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('pacto-column-input-decimal').type('50.00')
        cy.get('.checkmark-outline').click({ force: true })
        cy.get('#element-3-confirm').click({ force: true })
        //cy.get('.add-row').click({ force: true })
        //cy.get('.option-label').eq(0).click({ force: true })
        //cy.get('input[placeholder="Filtro..."]').type('ANUIDADE')
        //cy.get('.option-container').eq(0).click({ force: true })
        //cy.get('pacto-column-input-decimal').type('50.00')
        //cy.get('.checkmark-outline').click({ force: true })
        //cy.get('#element-3-confirm').click({ force: true })
        //cy.get('pacto-cat-button').eq(1).click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - DADOS CONTRATUAIS
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(0).type('NOME DA EMPRESA | CPS 2019')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('[label="Percentual da multa de cancelamento"]').type("50")
        cy.get('[label="Valor da mensalidade"]').type("500.00")
        cy.get('[label="Taxa de adesão"]').type("150.00")
        cy.get('[label="Fidelidade do plano (meses)"]').type("12")
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(1).click().type('CUSTO ADMINISTRATIVO DO CANCELAMENTO')
        cy.get('.option-container').eq(2).click({ force: true })
        // PÁGINA - CONFIGURAÇÕES AVANÇADAS
        cy.get('pacto-cat-button').eq(2).click({ force: true })
        cy.contains('Renovação automática').click({ force: true })
        cy.get('[label="Ativar renovação automática"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Renovar produtos obrigatórios"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.contains('Não renovar com parcela aberta').click({ force: true })
        cy.get('.mt-16 > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
    })

    // CASO DE TESTE 2: EDITAR CADASTRO - NORMAL
    it('Editar Plano - Normal', function () {
        cy.get('#input-busca-rapida').type('Teste automatizado')
        cy.wait(5000)
        cy.get('#ddaction-0').click({ force: true })
        cy.get('#ddAction-0-editar').click({ force: true })
        // PÁGINA - DADOS BÁSICOS
        cy.get('pacto-cat-form-input').type('Teste automatizado')
        cy.get('input[placeholder="__/__/____"]').eq(0).click({ force: true })
            .type('20012019')
        cy.get('input[placeholder="__/__/____"]').eq(1).click({ force: true })
            .type('20012026')
        cy.get('input[placeholder="__/__/____"]').eq(2).click({ force: true })
            .type('20012026')
        cy.get('pacto-cat-button').eq(0).click({ force: true })
        // PÁGINA - MODALIDADES
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('FAZ TUDO')
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - HORÁRIOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('1500.00')
        cy.get('#element-0-confirm').click({ force: true })
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('.option-label').eq(2).click({ force: true })
        cy.get('.option-container').eq(1).click({ force: true })
        cy.get('.aux-wrapper').type('500.00')
        cy.get('#element-1-confirm').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - PRODUTOS E SERVIÇOS
        cy.get('.add-row').click({ force: true })
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').type('ADESÃO PLANO RECORRENTE')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('pacto-column-input-decimal').type('50.00')
        cy.get('.checkmark-outline').click({ force: true })
        cy.get('#element-3-confirm').click({ force: true })
        //cy.get('.add-row').click({ force: true })
        //cy.get('.option-label').eq(0).click({ force: true })
        //cy.get('input[placeholder="Filtro..."]').type('ANUIDADE')
        //cy.get('.option-container').eq(0).click({ force: true })
        //cy.get('pacto-column-input-decimal').type('50.00')
        //cy.get('.checkmark-outline').click({ force: true })
        //cy.get('#element-3-confirm').click({ force: true })
        //cy.get('pacto-cat-button').eq(1).click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
        // PÁGINA - DADOS CONTRATUAIS
        cy.get('.option-label').eq(0).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(0).type('NOME DA EMPRESA | CPS 2019')
        cy.get('.option-container').eq(0).click({ force: true })
        cy.get('[label="Percentual da multa de cancelamento"]').type("150")
        cy.get('[label="Valor da mensalidade"]').type("500.00")
        cy.get('[label="Taxa de adesão"]').type("1150.00")
        cy.get('[label="Fidelidade do plano (meses)"]').type("12")
        cy.get('.option-label').eq(1).click({ force: true })
        cy.get('input[placeholder="Filtro..."]').eq(1).click().type('CUSTO ADMINISTRATIVO DO CANCELAMENTO')
        cy.get('.option-container').eq(2).click({ force: true })
        // PÁGINA - CONFIGURAÇÕES AVANÇADAS
        cy.get('pacto-cat-button').eq(2).click({ force: true })
        cy.contains('Renovação automática').click({ force: true })
        cy.get('[label="Ativar renovação automática"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Renovar produtos obrigatórios"] > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.contains('Não renovar com parcela aberta').click({ force: true })
        cy.get('.mt-16 > .cat-input-wrapper > label > .checkmark-outline').click({ force: true })
        cy.get('[label="Salvar Configurações"]').click({ force: true })
        cy.get('pacto-cat-button').eq(1).click({ force: true })
    })

    // CASO DE TESTE 3: EXCLUIR CADASTRO - RECORRÊNCIA
    it('Excluir Plano - Recorrência', function () {
        cy.get('#input-busca-rapida').type('Teste automatizado')
        cy.wait(5000)
        cy.get('#ddaction-0').click()
        cy.get('#ddAction-0-excluir').click()
    })

})